allowBuilds:
  "@parcel/watcher": false
  cpu-features: false
  esbuild: false
  protobufjs: false
  simple-git-hooks: true
  ssh2: false

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2

onlyBuiltDependencies:
  - simple-git-hooks
